### ISSUE TITLE
如何实现录制nico生放？

### ISSUE THREAD

**Issue by Etherrrr** [ssysm/StreamGetterV2#2]
如题，通过程序可以获取生放的视频流并使用`ffmpeg`进行录制，但是大约录制30s-1分钟左右时，服务器便返回403。想了解一下如何稳定录制nico的生放？

**Comment by ssysm** [comment]
感谢对Stream Getter的支持，有几个问题想问一下
- 目标操作系统？
- 是否是用的v2.1.1版本？
- 有收到过程序内报错吗？
- 如果没有，是否将程序保持最前运行呢？

感谢

**Comment by ssysm** [comment]
经过我这边的测试，好像并没有测试出任何异样，请确认一下本机的网络链接是否正常呢
![](https://storage.theeditorstudio.com/StreamGetter/20190307195107.png)

**Comment by Etherrrr** [comment]
系统是Win10，所用版本为v2.2.1.1，未收到过程序内报错，且始终保持前端运行。
经过在本机和服务器的多次测试，都是稳定连接55秒后断开，网络链接应该是没有问题的。
![snipaste_2019-03-08_23-45-03](https://user-images.githubusercontent.com/20717049/54038748-3e0b4200-41fc-11e9-8013-cb7088b67feb.png)

**Comment by ssysm** [comment]
抱歉咕了那么长时间呢(咕咕咕)
方便的话可以使用这个脚本
https://gist.github.com/ssysm/f5edbe06f2b7c127de42bb3a2e8bc9cc
来看一下您本地的报错, 核心算法也是基于这个脚本写的呢

安装一下node运行环境(11+)
新建一个空文件夹
命令行内运行 'npm install cherrio axios ws'
在脚本内修改要申请的流链接
然后'node script.js'

如果有报错请把错误信息截图发上来呢
感谢

**Comment by ssysm** [comment]
issue closed due to inactivity.
